// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_2ht8WX57XRUXONSsEQUnXEIRswX868',
    appId: '1:716256778604:web:46c5b43f1b1cb542447b49',
    messagingSenderId: '716256778604',
    projectId: 'cleanpro-6c7f2',
    authDomain: 'cleanpro-6c7f2.firebaseapp.com',
    storageBucket: 'cleanpro-6c7f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFJSYuKT94xAG9cDqL97iaSI0bRxHUoNc',
    appId: '1:716256778604:android:3d2abee3da5cdd37447b49',
    messagingSenderId: '716256778604',
    projectId: 'cleanpro-6c7f2',
    storageBucket: 'cleanpro-6c7f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWCkqr4FFsfwpcVyL7Uj2LUPjC7yF7VI',
    appId: '1:716256778604:ios:a1d0dbff2045f8a5447b49',
    messagingSenderId: '716256778604',
    projectId: 'cleanpro-6c7f2',
    storageBucket: 'cleanpro-6c7f2.firebasestorage.app',
    iosBundleId: 'com.example.cleanPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAWCkqr4FFsfwpcVyL7Uj2LUPjC7yF7VI',
    appId: '1:716256778604:ios:a1d0dbff2045f8a5447b49',
    messagingSenderId: '716256778604',
    projectId: 'cleanpro-6c7f2',
    storageBucket: 'cleanpro-6c7f2.firebasestorage.app',
    iosBundleId: 'com.example.cleanPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp_2ht8WX57XRUXONSsEQUnXEIRswX868',
    appId: '1:716256778604:web:7928a2ed42c58500447b49',
    messagingSenderId: '716256778604',
    projectId: 'cleanpro-6c7f2',
    authDomain: 'cleanpro-6c7f2.firebaseapp.com',
    storageBucket: 'cleanpro-6c7f2.firebasestorage.app',
  );
}
